In [1]:
import numpy as np

## Datatype & Attributes 

In [2]:
#ndarray - n-dimensional array
a1=np.array([1,2,3])
a1


array([1, 2, 3])

In [3]:
a2=np.array([[1,2,3],
            [2.3,3.4,5]])
a3=np.array([[[1,2,3],
             [2,3,4],
             [5,6,7]],
            [[2,3,4],
            [5,6,7],
            [8,9,10]]])

In [4]:
a2

array([[1. , 2. , 3. ],
       [2.3, 3.4, 5. ]])

In [5]:
a3

array([[[ 1,  2,  3],
        [ 2,  3,  4],
        [ 5,  6,  7]],

       [[ 2,  3,  4],
        [ 5,  6,  7],
        [ 8,  9, 10]]])

In [7]:
a1.shape

(3,)

In [8]:
a2.shape

(2, 3)

In [9]:
a3.shape

(2, 3, 3)

In [10]:
a1.ndim, a2.ndim,a3.ndim #number of dimensions

(1, 2, 3)

In [11]:
a1.dtype , a2.dtype, a3.dtype

(dtype('int64'), dtype('float64'), dtype('int64'))

In [12]:
a1.size, a2.size, a3.size

(3, 6, 18)

In [14]:
type(a1), type(a2),type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [16]:
#Create a df from NUmpy array
import pandas as pd
df=pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.0
1  2.3  3.4  5.0

## Create numpy array

In [17]:
sample_array=np.array([1,2,3])
sample_array

array([1, 2, 3])

In [19]:
ones=np.ones((2,3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [20]:
type(ones)

numpy.ndarray

In [22]:
zeros=np.zeros((2,3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [24]:
range_array=np.arange(0,10,2)

In [25]:
range_array


array([0, 2, 4, 6, 8])

In [26]:
random_array=np.random.randint(0,10,size=(3,5))

In [27]:
random_array


array([[8, 6, 6, 4, 3],
       [3, 3, 1, 1, 7],
       [8, 6, 7, 9, 1]])

In [28]:
np.random.random((5,3))

array([[0.84792181, 0.62479383, 0.20250252],
       [0.06481382, 0.87775112, 0.00514492],
       [0.83124647, 0.9222358 , 0.43230161],
       [0.74016998, 0.87203771, 0.08462185],
       [0.57183424, 0.19382056, 0.62492311]])

In [29]:
random_array_3=np.random.rand(5,3)
random_array_3

array([[0.22339922, 0.43986279, 0.78840258],
       [0.71130729, 0.10588151, 0.73790638],
       [0.46977464, 0.67670058, 0.77641688],
       [0.24683992, 0.96542805, 0.84589352],
       [0.51767286, 0.71161798, 0.81316631]])

In [32]:
np.random.seed(seed=0)
random_array_4=np.random.randint(10,size=(4,3))
random_array_4

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6]])